### ISSUE TITLE
Error generating constant

### ISSUE THREAD

**Issue by elmarsan** [aronmoles/i18n-next-generate-translations#1]
Currently if you have more than one translation in our translations.xml, at the moment of writing translations the constants writer has a fail and insert commas after each translation if it isn't the last one.

You can see that in the attached image.
![Screenshot 2020-12-01 at 22 27 40](https://user-images.githubusercontent.com/43180519/100799939-26d7a380-3426-11eb-9850-44d2c31e6787.png)

**Comment by aronmoles** [comment]
This bug is solved in new 1.0.3 version.

Thanks.
